---
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: aa
  checked: true
- value: ss
  checked: false
name: Nuevo ejercicio
